/insertion_path_node:
  ros__parameters:
    needle_offset_z: 0.167
    registration_topic: "/needle_poses"
    path_topic: "/needle_path"
    base_frame: "panda_link0"
# /**:
 #   ros__parameters:
  #      joint_names: [panda_joint1, panda_joint2, panda_joint3, panda_joint4, panda_joint5, panda_joint6, panda_joint7]
   #     joint_states_topic: /franka_state_controller/joint_states_desired
    #    target_pose_topic: /ik_target_pose
     #   command_topic: /ik_joint_goal
        #command_topic: /joint_position_example_controller/joint_command
       
   
